In [18]:
from statsbombpy import sb 
from mplsoccer import Pitch
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np

In [19]:
competitions = sb.competitions()

pd.set_option('display.max_rows',None)

competitions[
    [
        'competition_name',
        'season_name',
        'competition_id',
        'season_id'
    ]
]

           competition_name season_name  competition_id  season_id
0             1. Bundesliga   2023/2024               9        281
1             1. Bundesliga   2015/2016               9         27
2    African Cup of Nations        2023            1267        107
3          Champions League   2018/2019              16          4
4          Champions League   2017/2018              16          1
5          Champions League   2016/2017              16          2
6          Champions League   2015/2016              16         27
7          Champions League   2014/2015              16         26
8          Champions League   2013/2014              16         25
9          Champions League   2012/2013              16         24
10         Champions League   2011/2012              16         23
11         Champions League   2010/2011              16         22
12         Champions League   2009/2010              16         21
13         Champions League   2008/2009              16         41
14         Champions League   2006/2007              16         39
15         Champions League   2004/2005              16         37
16         Champions League   2003/2004              16         44
17         Champions League   1999/2000              16         76
18         Champions League   1972/1973              16        277
19         Champions League   1971/1972              16         71
20         Champions League   1970/1971              16        276
21             Copa America        2024             223        282
22             Copa del Rey   1983/1984              87         84
23             Copa del Rey   1982/1983              87        268
24             Copa del Rey   1977/1978              87        279
25  FA Women's Super League   2023/2024              37        281
26  FA Women's Super League   2020/2021              37         90
27  FA Women's Super League   2019/2020              37         42
28  FA Women's Super League   2018/2019              37          4
29       FIFA U20 World Cup        1979            1470        274
30           FIFA World Cup        2022              43        106
31           FIFA World Cup        2018              43          3
32           FIFA World Cup        1990              43         55
33           FIFA World Cup        1986              43         54
34           FIFA World Cup        1974              43         51
35           FIFA World Cup        1970              43        272
36           FIFA World Cup        1962              43        270
37           FIFA World Cup        1958              43        269
38        Frauen Bundesliga   2023/2024             135        281
39      Indian Super league   2021/2022            1238        108
40                  La Liga   2020/2021              11         90
41                  La Liga   2019/2020              11         42
42                  La Liga   2018/2019              11          4
43                  La Liga   2017/2018              11          1
44                  La Liga   2016/2017              11          2
45                  La Liga   2015/2016              11         27
46                  La Liga   2014/2015              11         26
47                  La Liga   2013/2014              11         25
48                  La Liga   2012/2013              11         24
49                  La Liga   2011/2012              11         23
50                  La Liga   2010/2011              11         22
51                  La Liga   2009/2010              11         21
52                  La Liga   2008/2009              11         41
53                  La Liga   2007/2008              11         40
54                  La Liga   2006/2007              11         39
55                  La Liga   2005/2006              11         38
56                  La Liga   2004/2005              11         37
57                  La Liga   1973/1974              11        278
58                   Liga F   2023/2024             182        281
59         Liga Profesional   1997/1998              81         48
60         Liga Profesional        1981              81        275
61                  Ligue 1   2022/2023               7        235
62                  Ligue 1   2021/2022               7        108
63                  Ligue 1   2015/2016               7         27
64      Major League Soccer        2023              44        107
65    North American League        1977             116         68
66                     NWSL        2023              49        107
67                     NWSL        2018              49          3
68           Premier League   2015/2016               2         27
69           Premier League   2003/2004               2         44
70                  Serie A   2015/2016              12         27
71                  Serie A   1986/1987              12         86
72            Serie A Women   2023/2024             131        281
73                UEFA Euro        2024              55        282
74                UEFA Euro        2020              55         43
75       UEFA Europa League   1988/1989              35         75
76        UEFA Women's Euro        2025              53        315
77        UEFA Women's Euro        2022              53        106
78        Women's World Cup        2023              72        107
79        Women's World Cup        2019              72         30

In [20]:
matches = sb.matches(competition_id=11, season_id=27)
matches.head()

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3825739,2016-01-17,17:00:00.000,5,1,available,unscheduled,2024-05-16T14:06:52.149840,NaN,20,...,France,187,Abelardo Fernández Antuña,Abelardo,1970-04-19,214,Spain,1.1.0,2,2
1,3825848,2015-09-23,20:00:00.000,2,2,available,unscheduled,2024-08-23T09:35:15.821559,NaN,5,...,Spain,221,José Luis Mendilibar Etxebarria,José Luis Mendilibar,1961-03-14,214,Spain,1.1.0,2,2
2,3825895,2015-09-23,22:00:00.000,2,0,available,unscheduled,2023-02-21T15:19:07.927548,NaN,5,...,Spain,21,Unai Emery Etxegoien,Unai Emery,1971-11-03,214,Spain,1.1.0,2,2
3,3825894,2016-05-01,18:15:00.000,0,2,available,unscheduled,2022-08-30T12:53:16.828350,NaN,36,...,Spain,1001036,Juan Eduardo Esnáider Belén,NaN,1973-03-05,11,Argentina,1.1.0,2,2
4,3825855,2016-05-02,20:30:00.000,3,1,available,unscheduled,2022-08-30T12:53:53.790835,NaN,36,...,Spain,677,Joan Francesc Ferrer Sicilia,Rubí,1970-02-05,214,Spain,1.1.0,2,2

In [21]:
matches.shape

(380, 55)

In [22]:
matches.columns

Index(['match_id', 'match_date', 'kick_off', 'home_score', 'away_score',
       'match_status', 'match_status_360', 'last_updated', 'last_updated_360',
       'match_week', 'competition_id', 'competition_country_name',
       'competition_name', 'competition', 'season_id', 'season',
       'home_team_id', 'home_team', 'home_team_gender', 'home_team_group',
       'home_team_country_id', 'home_team_country_name', 'away_team_id',
       'away_team', 'away_team_gender', 'away_team_group',
       'away_team_country_id', 'away_team_country_name',
       'competition_stage_id', 'competition_stage', 'stadium_id', 'stadium',
       'stadium_country_id', 'stadium_country_name', 'referee_id', 'referee',
       'referee_country_id', 'referee_country_name', 'home_managers',
       'away_managers', 'home_manager_id', 'home_manager_name',
       'home_manager_nickname', 'home_manager_dob', 'home_manager_country_id',
       'home_manager_country_name', 'away_manager_id', 'away_manager_name',
       'away_manager_nickname', 'away_manager_dob', 'away_manager_country_id',
       'away_manager_country_name', 'data_version', 'shot_fidelity_version',
       'xy_fidelity_version'],
      dtype='str')

In [23]:
#Gets the matches

matches[
    [
        'match_id',
        'home_team',
        'away_team',
        'match_date'

    ]
].head()

   match_id               home_team       away_team  match_date
0   3825739             Real Madrid  Sporting Gijón  2016-01-17
1   3825848              Levante UD           Eibar  2015-09-23
2   3825895              Las Palmas         Sevilla  2015-09-23
3   3825894  RC Deportivo La Coruña          Getafe  2016-05-01
4   3825855                  Málaga      Levante UD  2016-05-02

In [24]:
sample_matches = matches.head(10)
sample_matches.shape

(10, 55)

In [25]:
#We get the events per match 

all_events = []

for match_id in sample_matches['match_id']:

    print(f"Downloading {match_id}")

    match_events = sb.events(match_id=match_id)

    all_events.append(match_events)

Downloading 3825739
Downloading 3825848
Downloading 3825895
Downloading 3825894
Downloading 3825855
Downloading 3825908
Downloading 3825883
Downloading 3825900
Downloading 3825902
Downloading 3825876

In [26]:
type(all_events[0])

pandas.DataFrame

In [27]:
events = pd.concat(
    all_events,
    ignore_index=True
)

In [28]:
events.shape

(33145, 104)

In [29]:
events.columns

Index(['50_50', 'ball_receipt_outcome', 'ball_recovery_recovery_failure',
       'block_deflection', 'block_offensive', 'carry_end_location',
       'clearance_aerial_won', 'clearance_body_part', 'clearance_head',
       'clearance_left_foot',
       ...
       'bad_behaviour_card', 'dribble_no_touch', 'miscontrol_aerial_won',
       'pass_straight', 'shot_deflected', 'injury_stoppage_in_chain',
       'block_save_block', 'foul_committed_penalty', 'foul_won_penalty',
       'goalkeeper_punched_out'],
      dtype='str', length=104)

In [30]:
events.head()

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,...,bad_behaviour_card,dribble_no_touch,miscontrol_aerial_won,pass_straight,shot_deflected,injury_stoppage_in_chain,block_save_block,foul_committed_penalty,foul_won_penalty,goalkeeper_punched_out
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
events.info()

<class 'pandas.DataFrame'>
RangeIndex: 33145 entries, 0 to 33144
Columns: 104 entries, 50_50 to goalkeeper_punched_out
dtypes: float64(8), int64(8), object(52), str(36)
memory usage: 26.3+ MB

In [32]:
events['type_clean'] = (
    events['type']
    .astype(str)
    .str.strip()
)

In [33]:
#Debug
#events['type'].unique()

In [34]:
events['type_clean'].value_counts()

type_clean
Pass                 9720
Ball Receipt*        8302
Carry                6862
Pressure             2922
Ball Recovery         969
Duel                  776
Clearance             397
Dribble               350
Block                 349
Goal Keeper           325
Foul Committed        308
Foul Won              297
Miscontrol            296
Interception          290
Shot                  262
Dribbled Past         219
Dispossessed          213
Substitution           60
Half Start             40
Half End               40
Injury Stoppage        31
Tactical Shift         23
Starting XI            20
Player Off             16
Player On              16
Shield                 15
50/50                   8
Bad Behaviour           8
Offside                 7
Referee Ball-Drop       4
Name: count, dtype: int64

In [35]:
#Save copy
events_master = events.copy()

In [36]:
passes = events[events['type'] == 'Pass']
passes.shape

(9720, 105)

In [37]:
passes_by_player = (
    passes
    .groupby('player')
    .size()
    .reset_index(name='passes')
)

passes_by_player.head()

                      player  passes
0          Abdoul Karim Yoda      14
1    Adrián Embarba Blázquez      22
2    Adrián González Morales     101
3         Alberto Lora Ramos     126
4  Alejandro Arribas Garrido      37

In [38]:
passes_by_player.sort_values(
    by='passes',
    ascending=False
).head(15)

                                 player  passes
120                         Luka Modrić     127
3                    Alberto Lora Ramos     126
96          José Antonio García Rabasco     121
190                          Toni Kroos     120
90                 Jonathan Viera Ramos     119
164           Roberto Trashorras Gayoso     115
165                  Roque Mesa Quevedo     113
13                Antonio García Aranda     109
75                  Ismael López Blanco     108
119            Luis Hernández Rodríguez     106
33         Damián Nicolás Suárez Suárez     105
42                     David Juncà Reñé     104
2               Adrián González Morales     101
57             Federico Ricca Rostagnol     101
101  José María Martín-Bejarano Serrano      98

In [39]:
shots = events[
    events['type_clean'] == 'Shot'
]
shots.shape

(262, 105)

In [40]:
shots.head()

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,...,dribble_no_touch,miscontrol_aerial_won,pass_straight,shot_deflected,injury_stoppage_in_chain,block_save_block,foul_committed_penalty,foul_won_penalty,goalkeeper_punched_out,type_clean
3761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shot
3762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shot
3763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shot
3764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shot
3765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shot

In [41]:
shots_by_player = (
    shots
    .groupby('player')
    .size()
    .reset_index(name='shots')
)
shots_by_player.head()

                    player  shots
0        Abdoul Karim Yoda      1
1  Adrián Embarba Blázquez      5
2  Adrián González Morales      7
3           Alen Halilović      3
4     Ander Capa Rodríguez      2

In [42]:
xg_by_player = (
    shots
    .groupby('player')['shot_statsbomb_xg']
    .sum()
    .reset_index(name='xg')
)
xg_by_player.head(15)

                              player        xg
0                  Abdoul Karim Yoda  0.040446
1            Adrián Embarba Blázquez  0.313270
2            Adrián González Morales  0.300771
3                     Alen Halilović  0.345519
4               Ander Capa Rodríguez  0.125922
5            Antolín Alcáraz Viveros  0.199092
6      Antonio Manuel Luna Rodríguez  0.082669
7                   Antonio Rukavina  0.024055
8     Arnaldo Antonio Sanabria Ayala  0.473317
9               Borja González Tomás  1.405368
10              Carlos Castro García  0.070538
11             Carlos Martín Vigaray  0.221829
12                 Celso Borges Mora  0.115212
13  Charles Días Barbosa de Oliveira  1.904831
14             Christian Atsu Twasam  0.456587

In [43]:
pressures = events[
    events['type'] == 'Pressure'
]

In [44]:
pressures_by_player = (
    pressures
    .groupby('player')
    .size()
    .reset_index(name='pressures')
)
passes_by_player.head()

                      player  passes
0          Abdoul Karim Yoda      14
1    Adrián Embarba Blázquez      22
2    Adrián González Morales     101
3         Alberto Lora Ramos     126
4  Alejandro Arribas Garrido      37